# Generated by Django 4.2.3 on 2023-07-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('nutriscore_grade', models.CharField(max_length=1)),
                ('nutriscore_score', models.SmallIntegerField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
